In [2]:
import numpy as np
a = np.arange(15)
print("a = np.arange(15):", a)
a=a.reshape(3, 5)
print("a.reshape(3, 5):",a,sep="\n")

a = np.arange(15): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
a.reshape(3, 5):
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [2]:
print("a.shape=",a.shape)
print("a.ndim=",a.ndim)
print("a.dtype.name=",a.dtype.name)
print("a.itemsize=",a.itemsize)
print("a.size=",a.size)
print("type(a)=",type(a))

a.shape= (3, 5)
a.ndim= 2
a.dtype.name= int32
a.itemsize= 4
a.size= 15
type(a)= <class 'numpy.ndarray'>


In [3]:
b = np.array([6, 7, 8])
print(b)
print("type(b)=",type(b))

[6 7 8]
type(b)= <class 'numpy.ndarray'>


In [4]:
import numpy as np
array = np.array([[1,2,3],[2,3,4]])
print(array)

[[1 2 3]
 [2 3 4]]


In [5]:
 import numpy as np
 a = np.array([2,3,4])
 print("a=", a)
 print("a.dtype:",a.dtype)
 b = np.array([1.2, 3.5, 5.1])
 print("b=", b)
 print("b.dtype:", b.dtype)

a= [2 3 4]
a.dtype: int32
b= [1.2 3.5 5.1]
b.dtype: float64


In [6]:
b = np.array([(1.5,2,3), (4,5,6)])
print("b=",b,sep="\n")
print("b.dtype:", b.dtype)

b=
[[1.5 2.  3. ]
 [4.  5.  6. ]]
b.dtype: float64


In [7]:
c = np.array( [ [1,2], [3,4] ],dtype=complex )
print("c=",c,sep="\n")
print("c.dtype:", c.dtype)

c=
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
c.dtype: complex128


In [8]:
c = np.array( [ [1+3j,2-2j], [3-5j,4] ],dtype=complex )
print("c=",c,sep="\n")
print("c.dtype:", c.dtype)

c=
[[1.+3.j 2.-2.j]
 [3.-5.j 4.+0.j]]
c.dtype: complex128


In [9]:
print("np.zeros((3,4)):",np.zeros((3,4)),sep="\n")
print("\nnp.ones((2,3,4), dtype=np.int16 )",np.ones((2,3,4), dtype=np.int16 ),sep="\n")
print("\nnp.empty((2,3))",np.empty((2,3)),sep="\n")

np.zeros((3,4)):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

np.ones((2,3,4), dtype=np.int16 )
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]

np.empty((2,3))
[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]


In [10]:
print(np.arange( 10, 30, 5 ))
print(np.arange( 0, 2, 0.3 )) # it accepts float arguments

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [11]:
from numpy import pi
print(np.linspace( 0, 2, 9 )) # 從 0 到 2 均勻產生9個數字
x = np.linspace( 0, 2*pi, 100 ) # useful to evaluate function at lots of points
f = np.sin(x)
import matplotlib.pyplot as plt
plt.plot(x,f)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [12]:
a = np.arange(6) # 1d array
print("1D array:", a)

b = np.arange(12).reshape(4,3) # 2d array
print("\n2D array:", b,sep="\n")

c = np.arange(24).reshape(2,3,4) # 3d array
print("\n3D array:", c,sep="\n")

1D array: [0 1 2 3 4 5]

2D array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

3D array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [3]:
print(np.arange(10000))
print(np.arange(10000).reshape(100,100))

[   0    1    2 ... 9997 9998 9999]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [13]:
import sys
np.set_printoptions(threshold=sys.maxsize)

In [14]:
a = np.array( [20,30,40,50] ); print("a=",a)
b = np.arange( 4 ); print("b=",b)
c = a-b; print("c=a-b=",c)
print("b**2=",b**2)
print("10*np.sin(a)=",10*np.sin(a))
print("a<35:",a<35)

a= [20 30 40 50]
b= [0 1 2 3]
c=a-b= [20 29 38 47]
b**2= [0 1 4 9]
10*np.sin(a)= [ 9.12945251 -9.88031624  7.4511316  -2.62374854]
a<35: [ True  True False False]


In [15]:
A = np.array([[1,1],[0,1]])
B = np.array( [[2,0],[3,4]] )
print("A * B=", A * B,sep="\n") # elementwise product
print("\nA @ B=", A @ B,sep="\n") # matrix product
print("\nA.dot(B)", A.dot(B),sep="\n") #another matrix product 

A * B=
[[2 0]
 [0 4]]

A @ B=
[[5 4]
 [3 4]]

A.dot(B)
[[5 4]
 [3 4]]


In [17]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
print(a)
b += a
print(b)
a += b  # b is not automatically converted to integer type
print(a)

[[3 3 3]
 [3 3 3]]
[[3.9836401  3.78282854 3.01525696]
 [3.28518701 3.42615116 3.48539531]]


TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [18]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
print("b.dtype:",b.dtype)
c = a+b
print("c=",c,"\tc.dtype:",c.dtype)
d = np.exp(c*1j)
print(d)
print(d.dtype)

b.dtype: float64
c= [1.         2.57079633 4.14159265] 	c.dtype: float64
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
complex128


In [19]:
B = np.arange(3)
print(B)
print("\nnp.exp(B):",np.exp(B),sep="\n")
print("\nnp.sqrt(B):",np.sqrt(B),sep="\n")
C = np.array([2., -1., 4.])
print("\nnp.add(B, C):",np.add(B, C),sep="\n")

[0 1 2]

np.exp(B):
[1.         2.71828183 7.3890561 ]

np.sqrt(B):
[0.         1.         1.41421356]

np.add(B, C):
[2. 0. 6.]


In [20]:
a = np.random.random((2,3))
print(a)
print("a.sum()=",a.sum())
print("a.min()=",a.min())
print("a.max()=",a.max())

[[0.18024554 0.94659664 0.2557115 ]
 [0.83032893 0.93321598 0.78095927]]
a.sum()= 3.927057861803295
a.min()= 0.1802455367799911
a.max()= 0.9465966357709371


In [22]:
b = np.arange(12).reshape(3,4)
print(b)
print("b.sum(axis=0):",b.sum(axis=0)) # sum of each column
print("b.min(axis=1):",b.min(axis=1)) # min of each row
print("b.cumsum(axis=0):",b.cumsum(axis=0),sep="\n")
print("b.cumsum(axis=1):",b.cumsum(axis=1),sep="\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b.sum(axis=0): [12 15 18 21]
b.min(axis=1): [0 4 8]
b.cumsum(axis=0):
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]
b.cumsum(axis=1):
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [23]:
a=np.array([10,20,30,40])
b=np.arange(4)
print("a=",a)
print("b=",b)
c=a-b
print("a-b=",c)
c=a+b
print("a+b=",c)
c=a*b
print("a*b=",c)
c=b**2
print("b**2=",c)
c=10*np.sin(a)
print("10*np.sin(a)=",c)
print("b<3=",b<3)

a= [10 20 30 40]
b= [0 1 2 3]
a-b= [10 19 28 37]
a+b= [10 21 32 43]
a*b= [  0  20  60 120]
b**2= [0 1 4 9]
10*np.sin(a)= [-5.44021111  9.12945251 -9.88031624  7.4511316 ]
b<3= [ True  True  True False]


In [21]:
a=np.array([[1,1],[0,1]])
print("a=",a,sep="\n")
b=np.arange(4).reshape((2,2))
print("b=",b,sep="\n")
c_dot = np.dot(a,b)
print("np.dot(a,b)=",c_dot,sep="\n")
c_dot_2 = a.dot(b)
print("a.dot(b)=",c_dot_2,sep="\n")
print("np.sum(b)=",np.sum(b))
print("np.min(b)=",np.min(b))
print("np.max(b)=",np.max(b))

a=
[[1 1]
 [0 1]]
b=
[[0 1]
 [2 3]]
np.dot(a,b)=
[[2 4]
 [2 3]]
a.dot(b)=
[[2 4]
 [2 3]]
np.sum(b)= 6
np.min(b)= 0
np.max(b)= 3


In [24]:
print("b=",b,sep="\n")
print("np.sum(b,axis=1)=",np.sum(b,axis=1))
print("np.min(b,axis=0)=",np.min(b,axis=0))
print("np.max(b,axis=1)=",np.max(b,axis=1))

b=
[0 1 2 3]


AxisError: axis 1 is out of bounds for array of dimension 1

In [25]:
A = np.arange(2,14).reshape((3,4)) 
print("A=",A,sep="\n")
print("np.argmin(A)=",np.argmin(A))
print("np.argmax(A)=",np.argmax(A))

A=
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
np.argmin(A)= 0
np.argmax(A)= 11


In [26]:
A = np.arange(2,14).reshape((3,4)) 
print("A=",A,sep="\n")
print("np.argmin(A)=",np.argmin(A))
print("np.argmax(A)=",np.argmax(A))
print("np.mean(A)=",np.mean(A))
print("A.mean()=",A.mean())
print("np.average(A)=",np.average(A))
#print("A.average()=",A.average())
print("np.median(A)=",np.median(A))    
#print("A.median()=",A.median())
print("np.cumsum(A)=",np.cumsum(A)) 
print("np.diff(A)=",np.diff(A),sep="\n") 

A=
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
np.argmin(A)= 0
np.argmax(A)= 11
np.mean(A)= 7.5
A.mean()= 7.5
np.average(A)= 7.5
np.median(A)= 7.5
np.cumsum(A)= [ 2  5  9 14 20 27 35 44 54 65 77 90]
np.diff(A)=
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [27]:
a = np.arange(10)**3
print("a=",a)
print("a[2]=",a[2])
print("a[2:5]=",a[2:5])
a[:6:2] = -1000 # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
print("a=",a)
print("a[ : :-1]=",a[ : :-1]) # reversed a
print("a=",a)
for i in a:
    print(i**(1/3.))

a= [  0   1   8  27  64 125 216 343 512 729]
a[2]= 8
a[2:5]= [ 8 27 64]
a= [-1000     1 -1000    27 -1000   125   216   343   512   729]
a[ : :-1]= [  729   512   343   216   125 -1000    27 -1000     1 -1000]
a= [-1000     1 -1000    27 -1000   125   216   343   512   729]
nan
1.0
nan
3.0
nan
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


C:\Users\T30518\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in power
  # Remove the CWD from sys.path while we load stuff.


In [28]:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
print("b=",b,sep="\n")
print("b[2,3]=",b[2,3])
print("b[0:5, 1]=",b[0:5, 1]) # each row in the second column of b
print("b[ : ,1]=",b[ : ,1]) # equivalent to the previous example
print("b[1:3, : ]=",b[1:3, : ],sep="\n") # each column in the second and third row of b
print("b[-1]=",b[-1]) # the last row. Equivalent to b[-1,:]

b=
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
b[2,3]= 23
b[0:5, 1]= [ 1 11 21 31 41]
b[ : ,1]= [ 1 11 21 31 41]
b[1:3, : ]=
[[10 11 12 13]
 [20 21 22 23]]
b[-1]= [40 41 42 43]


In [ ]:
c = np.array( [[[  0,  1,  2],   # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])
print("c.shape=",c.shape)
print(c[1,...]) # same as c[1,:,:] or c[1]
print(c[...,2]) # same as c[:,:,2]

In [ ]:
for row in b:
    print(row)

In [ ]:
for element in b.flat:
    print(element)

In [ ]:
A = np.arange(3,15) # array([3,4,5,…,12,13,14])
print(A[3]) # 6
B = np.arange(3,15).reshape((3,4))
print(B)
print(B[2]) # [11,12,13,14]
print(B[1][1]) # 8
print(B[1,1]) # 8
print(B[1,1:3]) # [8,9]
for row in B: # 逐列迴圈
    print(row)
for column in B.T: # 逐行迴圈
    print(column)
for item in B.flat: # 逐元素迴圈
    print(item)

In [ ]:
a = np.floor(10*np.random.random((3,4)))
print("a=",a,sep="\n")
print("a.shape=",a.shape)

In [ ]:
print("a.ravel():",a.ravel()) # returns the array, flattened
print("a.reshape(6,2):",a.reshape(6,2),sep="\n")  # returns the array with a modified shape
print("a.T:",a.T,sep="\n") # returns the array, transposed
print("a.T.shape:",a.T.shape)
print("a.shape:",a.shape)

In [ ]:
print("a=",a,sep="\n")
a.resize((2,6))
print("a=",a,sep="\n")

In [ ]:
print("a.reshape(3,-1):",a.reshape(3,-1),sep="\n") 
print("a.reshape(-1,3):",a.reshape(-1,3),sep="\n")

In [ ]:
a = np.floor(10*np.random.random((2,2)))
print("a=",a,sep="\n")
b = np.floor(10*np.random.random((2,2)))
print("b=",b,sep="\n")
c = np.vstack((a,b))
print("c",c,sep="\n")
d = np.hstack((a,b))
print("d",d,sep="\n")

In [ ]:
e = np.column_stack((a,b)) # with 2D arrays
print("e",e,sep="\n")
a = np.array([4.,2.])
b = np.array([3.,8.])
f=np.column_stack((a,b)) 
print("f",f,sep="\n")

In [ ]:
import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])
C = np.vstack((A,B)) # vertical stack   
print(C)
print(A.shape,C.shape)

In [ ]:
D = np.hstack((A,B))       # horizontal stack
print(D)
print(A.shape,D.shape)

In [ ]:
print(A.shape)
print(A)
print(A.T)
E=A[np.newaxis,:]
print(E.shape)
print(E)
print(E.T)

In [ ]:
A=A[np.newaxis,:]
B=B[np.newaxis,:]
C = np.concatenate((A,B,B,A),axis=0)
print(C)
D = np.concatenate((A,B,B,A),axis=1)
print(D)

In [ ]:
A = np.arange(12).reshape((3, 4))
print(np.split(A, 2, axis=1))

In [ ]:
print(np.split(A, 3, axis=0))

In [ ]:
print(np.split(A, 3, axis=1))

In [ ]:
print(np.array_split(A, 3, axis=1))

In [ ]:
print(np.vsplit(A, 3)) #等於 print(np.split(A, 3, axis=0))
print(np.hsplit(A, 2)) #等於 print(np.split(A, 2, axis=1))

In [ ]:
a = np.arange(12)
b = a # no new object is created
print(b is a) # a and b are two names for the same ndarray object
b.shape = 3,4    # changes the shape of a
print("a.shape:",a.shape)

In [ ]:
def f(x):
    print("call, id(x)=",id(x))
    x[0,0]=9
    print("call,change value, id(x)=",id(x))
    x=123
    print("call,change type, id(x)=",id(x))  
print("before call, a=",a,sep="\n")
print("before call, id(a)=",id(a)) # id is a unique identifier of an object
f(a)
print("after call, a=",a,sep="\n")
print("after call, id(a)=",id(a))

In [ ]:
c = a.view()
print(c is a)
print(c.base is a) # c is a view of the data owned by a
print(c.flags.owndata)
c.shape = 2,6 # a's shape doesn't change
print(a.shape)
c[0,4] = 1234 # a's data changes
print(a)

In [ ]:
s = a[:,1:3] # spaces added for clarity; could also be written "s = a[:,1:3]"
s[:] = 10 # s[:] is a view of s. Note the difference between s=10 and s[:]=10
print(a)

In [ ]:
d = a.copy() # a new array object with new data is created
print(d is a)
print(d.base is a) # d doesn't share anything with a
d[0,0] = 9999
print(a)

In [ ]:
a = np.arange(int(1e8))
b = a[:100].copy()
del a # the memory of ``a`` can be released.

In [ ]:
a = np.arange(4)
b = a;c = a;d = b
d[0] = 11; print(a)
print(b is a, c is a, d is a, c is b, d is b, d is c)

In [ ]:
b = a.copy()    # deep copy
print(b)        # array([11  1  2  3])
a[3] = 44
print(a)        # array([11  1  2  44])
print(b)        # array([11  1  2  3])

In [ ]:
a = np.arange(12)**2
i = np.array([1,1,3,8,5])
print(a[i])
j = np.array([[3,4],[9,7]])
print(a[j])

In [ ]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)
print(a.transpose())
print(np.linalg.inv(a))
u = np.eye(2) # unit 2x2 matrix; "eye" represents "I"
print(u)
j = np.array([[0.0, -1.0], [1.0, 0.0]])
print(j @ j) # matrix product
np.trace(u) # trace
y = np.array([[5.], [7.]])
np.linalg.solve(a, y)
np.linalg.eig(j)